name: spine_flutter
description: The official Spine Flutter Runtime to load, display and interact with Spine animations.
version: 4.3.0
homepage: https://esotericsoftware.com
repository: https://github.com/esotericsoftware/spine-runtimes
issue_tracker: https://github.com/esotericsoftware/spine-runtimes/issues
documentation: https://esotericsoftware.com/spine-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  inject_js: ^2.0.0
  js: ^0.6.5
  meta: ^1.10.0
  http: ^1.1.0
  path: ^1.8.2
  crypto: ^3.0.3
  universal_ffi: ^1.1.3

dev_dependencies:
  ffigen: ^10.0.0
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:

  assets:
    - lib/assets/libspine_flutter.js
    - lib/assets/libspine_flutter.wasm
