name: Formatting

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v3

    - name: Setup clang-format
      run: |
        # Install libtinfo5 (required by the Ubuntu 18.04 binary)
        # Create a symlink since Ubuntu 24.04 has libtinfo6
        sudo apt-get update
        sudo apt-get install -y libtinfo6
        sudo ln -sf /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5
        
        # Download clang-format 18.1.8 binary directly
        wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang%2Bllvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz
        tar -xf clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz
        
        # Install clang-format binary to /usr/bin where it will be found first
        sudo cp clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04/bin/clang-format /usr/bin/clang-format
        sudo chmod +x /usr/bin/clang-format
        
        # Verify version and location
        which clang-format
        clang-format --version

    - name: Install dotnet
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: "8.0.x"

    - name: Install Node and dependencies
      uses: actions/setup-node@v3
      with:
        node-version: "24"

    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "16"

    - name: Install Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: '4.3.2'
    - run: haxelib install formatter

    - name: Install Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.8.1'

    - name: Check dart format version
      run: |
        dart format --version

    - name: Format
      run: |
        ./formatters/format-cpp.sh
        ./formatters/format-csharp.sh
        ./formatters/format-dart.sh
        ./formatters/format-haxe.sh
        ./formatters/format-java.sh
        ./formatters/format-ts.sh
        git diff > format-diff.txt

    - name: Archive formatting result
      uses: actions/upload-artifact@v4
      with:
        name: format-diff
        path: format-diff.txt

    - name: Fail on format changes
      run: |
        git ls-files -m
        if [[ `git ls-files -m` ]]; then echo "Detected formatting errors!" & exit 1; fi